version: '2'
services:
  php:
    build: ./docker/php/ 
    container_name: php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '20080:80'
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=10web
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    restart: always
    ports:
      - "32769:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
        - "11211:11211"
    restart: always
